# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b52ba2aef7ae2b2a446c35327186b465ba10e688dc995e4a9f8c751f9d869af3c73e075ffe47934e74faa94aa3efdc9c69fb500dd2bb24a1d1d88b37ea148afa

test:
  secret_key_base: 2e4a704fa2bacacdd581829372f64769fb2b2e88b5d555b37f1b7f15cc50aaa6925a121d7e49a65e953999d1b9922612958e44cbdf0a81c90ec60fb8bfaef172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
