

  # Spree Editor TinyMCE Configuration
#
# These are the options that will automatically be passed into the tinyMCE.init function
# whenever TinyMCE is loaded in one of your spree pages. Please edit this file to
# customise your TinyMCE setup in your spree installation. If you wish to see the full
# range of configuration options then please go here:
#
#    http://www.tinymce.com/wiki.php/configuration

# TinyMCE Options
menubar: false
mode: "exact"
theme: "modern"
skin: "lightgray"
schema: "html5-strict"
element_format: "html"
resize: true
plugins:
  - layer
  - table
  - insertdatetime
  - preview
  - media
  - searchreplace
  - contextmenu
  - paste
  - directionality
  - fullscreen
  - noneditable
  - visualchars
  - nonbreaking
  - template
  - advlist autolink lists link image charmap print preview hr anchor pagebreak
  - searchreplace wordcount visualblocks visualchars code fullscreen
  - insertdatetime media nonbreaking save table contextmenu directionality
  - emoticons template paste textcolor colorpicker textpattern imagetools

# Each line is a toolbar
toolbar:
  - cut copy paste pastetext pasteword | search replace | undo redo | link unlink anchor image cleanup help code | insertdate inserttime preview | charmap media 
  - styleselect formatselect fontselect fontsizeselect | forecolor backcolor | bold italic underline strikethrough | justifyleft justifycenter justifyright justifyfull | sub sup | bullist numlist | outdent indent blockquote | tablecontrols | hr removeformat visualaid
  - fullscreen | print preview media 
  



